language: ruby
rvm:
  - 2.2.0

before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare

script:
  - export RAILS_ENV=test
  - bundle exec rspec spec/
